name: mamba_env2
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - matplotlib
  - pip
  
  - bioimageio.core
  - jupyter
  - pytorch=2.5.1
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - scikit-image>=0.24
  - pip:
    - nd2
    - pynrrd
    - setuptools_scm
    - scyjava 
    - bioformats_jar
    - "cellpose[gui]"
    - aicsimageio